services:
  - type: web
    name: aprima-controle-financeiro
    env: python
    buildCommand: |
      apt-get update && apt-get install -y locales && locale-gen pt_BR.UTF-8 && /opt/render/project/src/.venv/bin/pip install -r requirements.txt && /opt/render/project/src/.venv/bin/python -m spacy download pt_core_news_sm
    startCommand: /opt/render/project/src/.venv/bin/python app.py
    envVars:
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: ADMIN_NUMERO
        sync: false
